[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
indicatif = { version = "0.17.9", features = ["rayon"] }
petgraph = "0.6.5"
rayon = "1.10.0"
regex = "1.11.1"

[profile.dev]
opt-level = 0
